name: LobbyPlugin
main: org.derjannik.bashlobby.bashlobby
description: BashLobby
version: 1.0
api-version: 1.21
commands:
  lobby:
    description: Main command for the lobby plugin
  report:
    description: Report a player
  friend:
    description: Manage friends
  party:
    description: Manage parties
  clan:
    description: Manage clans
permissions:
  lobby.use:
    description: Allows use of the lobby command
    default: true
  report.use:
    description: Allows use of the report command
    default: true
  friend.use:
    description: Allows use of the friend command
    default: true
  party.use:
    description: Allows use of the party command
    default: true
  clan.use:
    description: Allows use of the clan command
    default: true